version: 2
updates:
  # Enable version updates for npm (main package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    reviewers:
      - "sekretk"
    assignees:
      - "sekretk"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    allow:
      # Allow both direct and indirect updates
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Group dependency updates to reduce PR noise
    groups:
      nx:
        patterns:
          - "@nx/*"
        update-types:
          - "minor"
          - "patch"
      nestjs:
        patterns:
          - "@nestjs/*"
        update-types:
          - "minor"
          - "patch"
      react:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "@playwright/*"
        update-types:
          - "minor"
          - "patch"
      eslint:
        patterns:
          - "*eslint*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    reviewers:
      - "sekretk"
    assignees:
      - "sekretk"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    reviewers:
      - "sekretk"
    assignees:
      - "sekretk"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "backend"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    reviewers:
      - "sekretk"
    assignees:
      - "sekretk"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"
