version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: delbot-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - delbot-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: delbot-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - delbot-network

networks:
  delbot-network:
    driver: bridge

# Development override example
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
# 
# version: '3.8'
# services:
#   backend:
#     environment:
#       - NODE_ENV=development
#     volumes:
#       - ./backend/src:/app/backend/src
#   frontend:
#     volumes:
#       - ./frontend/src:/app/frontend/src
