apiVersion: apps/v1
kind: Deployment
metadata:
  name: delbot-backend
  labels:
    app: delbot-backend
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delbot-backend
  template:
    metadata:
      labels:
        app: delbot-backend
        component: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/sekretk/delbot/backend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      imagePullSecrets:
      - name: ghcr-secret
