apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delbot-ingress
  annotations:
    # NGINX Ingress Controller
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    
    # SSL certificate temporarily disabled due to cluster ACME pathType restrictions
    # cert-manager.io/cluster-issuer: "letsencrypt-fixed"
    
    # Security headers are handled by cluster configuration
    
    # Rate limiting
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    
spec:
  ingressClassName: nginx
  # TLS temporarily disabled - re-enable when cluster ACME issues are resolved
  # tls:
  # - hosts:
  #   - delbot.boysthings.top
  #   secretName: delbot-tls-secret
  rules:
  - host: delbot.boysthings.top
    http:
      paths:
      # Frontend - serve React app
      - path: /
        pathType: Prefix
        backend:
          service:
            name: delbot-frontend-service
            port:
              number: 80
      # Backend API - all /api requests go to backend
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: delbot-backend-service
            port:
              number: 3000
      # Backend health check
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: delbot-backend-service
            port:
              number: 3000
